services:
  # Solo dejamos el Bot
  bot-local:
    build: .
    container_name: jarvis-bot-2026-dev
    restart: always
    env_file:
      - .env
    networks:
      - dev-network # <--- Se une a la red de postgres-main
    healthcheck:
      test: ["CMD", "python", "-c", "import psycopg2, os; psycopg2.connect(host=os.getenv('POSTGRES_HOST'), database=os.getenv('POSTGRES_DB'), user=os.getenv('POSTGRES_USER'), password=os.getenv('POSTGRES_PASSWORD'))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  # La red donde ya corre 'postgres-main' que descubrimos con el inspect
  dev-network:
    external: true
    name: home-server-net
