services:
  # Solo dejamos el Bot
  bot-local:
    build: .
    container_name: jarvis-bot-2026-dev
    restart: always
    env_file:
      - .env
    networks:
      - dev-network # <--- Se une a la red de postgres-main

networks:
  # La red donde ya corre 'postgres-main' que descubrimos con el inspect
  dev-network:
    external: true
    name: home-server-net
